<?php

namespace BlogBundle\Entity;

/**
 * AdvertTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertTagRepository extends \Doctrine\ORM\EntityRepository
{
}
