
security:
    encoders:
        UserBundle\Entity\User:
            algorithm: plaintext

    providers:
      our_db_provider:
          entity:
              class: UserBundle:User
              property: username
    firewalls:
        
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:   ^/
            anonymous: true
            provider: our_db_provider
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: blog_home
            logout:
                path:   logout
                target: /blog
