blog_home:
    path:      /{page}
    defaults:
        _controller: BlogBundle:Advert:index
        page:        1
    requirements:
        page: \d*

blog_articles:
    path:      /articles/{page}
    defaults:
        _controller: BlogBundle:Advert:list
        page:        1
    requirements:
        page: \d*

blog_view:
    path:      /article/{id}
    defaults:  { _controller: BlogBundle:Advert:view }
    requirements:
        id: \d+

blog_categories:
    path:      /categories/{page}
    defaults:
        _controller: BlogBundle:Advert:listCategory
        page:        1
    requirements:
        id: \d*

blog_category:
    path:      /category/{id}
    defaults:  { _controller: BlogBundle:Advert:category }
    requirements:
        id: \d+

blog_add:
    path:      /add
    defaults:  { _controller: BlogBundle:Advert:add }

blog_edit:
    path:      /edit/{id}
    defaults:  { _controller: BlogBundle:Advert:edit }
    requirements:
        id: \d+

blog_delete:
    path:      /delete/{id}
    defaults:  { _controller: BlogBundle:Advert:delete }
    requirements:
        id: \d+
