blog_home:
    path:      /{page}
    defaults:
        _controller: BlogBundle:Advert:index
        page:        1
    requirements:
        page: \d*

blog_articles:
    path:      /articles/{page}
    defaults:
        _controller: BlogBundle:Advert:list
        page:        1
    requirements:
        page: \d*

blog_view:
    path:      /article/{id}
    defaults:  { _controller: BlogBundle:Advert:view }
    requirements:
        id: \d+

blog_category:
    path:      /category/{id}
    defaults:  { _controller: BlogBundle:Advert:viewCategory }
    requirements:
        id: \d+

blog_categories:
    path:      /categories/{page}
    defaults:
        _controller: BlogBundle:Advert:listCategory
        page:        1
    requirements:
        id: \d*
blog_tags:
    path:      /tags/{page}
    defaults:
        _controller: BlogBundle:Advert:listTag
        page:        1
    requirements:
        id: \d*

blog_add:
    path:      admin/add
    defaults:  { _controller: BlogBundle:Advert:add }

blog_edit:
    path:      admin/edit/{id}
    defaults:  { _controller: BlogBundle:Advert:edit }
    requirements:
        id: \d+

blog_delete:
    path:      admin/delete/{id}
    defaults:  { _controller: BlogBundle:Advert:delete }
    requirements:
        id: \d+

category_edit:
    path:      admin/category/edit/{id}
    defaults:  { _controller: BlogBundle:Advert:editCategory }
    requirements:
        id: \d+

category_delete:
    path:      admin/category/delete/{id}
    defaults:  { _controller: BlogBundle:Advert:deleteCategory }
    requirements:
        id: \d+

tag_delete:
    path:      admin/tag/delete/{id}
    defaults:  { _controller: BlogBundle:Advert:deleteTag }
    requirements:
        id: \d+
