user_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Advert:index }

login:
    path: /login
    defaults: { _controller: UserBundle:Security:login }

login_check:
    path: /login_check
    defaults: { _controller: UserBundle:Security:loginCheck }

logout:
    path: /logout
